using System;
using System.Collections.Generic;
using System.Linq;
using Dagmay.Core.Development;

namespace Dagmay.Core.Appraisal
{
    public sealed class V43ProposalTrustRegistry
    {
        private readonly Dictionary<string,V43ProposalAttestation> _pending=new Dictionary<string,V43ProposalAttestation>(StringComparer.Ordinal);
        private readonly string _saveId,_worldId,_storeSetId;
        public V43ProposalTrustRegistry(string saveId,string worldId,string storeSetId){_saveId=saveId;_worldId=worldId;_storeSetId=storeSetId;}
        public V43ProposalAttestation Attest(ContextualAppraisalRequest request,GroundedCompoundAppraisalProposal proposal)
        {
            if(_pending.Count>=ContextualProvisionalAdmissionSource.MaximumPendingAttestations)throw new InvalidOperationException("Attestation capacity reached");
            var exact=new GroundedCompoundAppraisalSynthesizer().Synthesize(request);
            if(exact.Fingerprint!=proposal.Fingerprint||exact.ToDeterministicJson()!=proposal.ToDeterministicJson())throw new ArgumentException("Proposal is not exact synthesizer output");
            var fp=ContextualProvisionalAdmissionSource.Hash(string.Join("|",proposal.Fingerprint,request.CurrentSeed.CheckpointGeneration,request.CurrentSeed.CheckpointFingerprint,_saveId,_worldId,_storeSetId));
            var a=new V43ProposalAttestation(proposal,request.CurrentSeed.CheckpointGeneration,request.CurrentSeed.CheckpointFingerprint,_saveId,_worldId,_storeSetId,fp);_pending.Add(fp,a);return a;
        }
        internal void Verify(V43ProposalAttestation a,GroundedCompoundAppraisalProposal p){if(!_pending.TryGetValue(a.Fingerprint,out var x)||!ReferenceEquals(x,a)||a.ProposalFingerprint!=p.Fingerprint)throw new InvalidOperationException("Untrusted v43 attestation");}
        internal void Consume(V43ProposalAttestation a){if(!_pending.TryGetValue(a.Fingerprint,out var x)||!ReferenceEquals(x,a))throw new InvalidOperationException("Untrusted v43 attestation");_pending.Remove(a.Fingerprint);}
        public int Count=>_pending.Count;
    }

    public sealed class DialogueAdmissionTrustRegistry
    {
        private readonly Dictionary<string,ContextualAdmittedDialogueEventReceipt> _pending=new Dictionary<string,ContextualAdmittedDialogueEventReceipt>(StringComparer.Ordinal); private readonly string _save,_world,_stores;
        public DialogueAdmissionTrustRegistry(string saveId,string worldId,string storeSetId){_save=saveId;_world=worldId;_stores=storeSetId;}
        public ContextualAdmittedDialogueEventReceipt Create(string eventId,string eventHash,string utteranceId,string conversationId,string speakerId,string? recipientId,IEnumerable<string> audienceIds,string exactTextHash,long displayedTick,long admittedTick,long checkpointGeneration,string checkpointFingerprint){if(_pending.Count>=64)throw new InvalidOperationException("Receipt capacity");var fp=ContextualProvisionalAdmissionSource.Hash(string.Join("|",eventId,eventHash,utteranceId,conversationId,speakerId,exactTextHash,displayedTick,admittedTick,checkpointGeneration,checkpointFingerprint,_save,_world,_stores));var r=new ContextualAdmittedDialogueEventReceipt(eventId,eventHash,utteranceId,conversationId,speakerId,recipientId,audienceIds,exactTextHash,displayedTick,admittedTick,checkpointGeneration,checkpointFingerprint,_save,_world,_stores,fp);_pending.Add(fp,r);return r;}
        internal void Verify(ContextualAdmittedDialogueEventReceipt r){if(!_pending.TryGetValue(r.Fingerprint,out var x)||!ReferenceEquals(x,r))throw new InvalidOperationException("Untrusted dialogue receipt");}
        internal void Consume(ContextualAdmittedDialogueEventReceipt r){Verify(r);_pending.Remove(r.Fingerprint);} public int Count=>_pending.Count;
    }

    public sealed class ReactionPathClaimRegistry
    { private readonly Dictionary<string,(ProvisionalReactionPath Path,string Claim)>_claims=new Dictionary<string,(ProvisionalReactionPath,string)>(StringComparer.Ordinal); private static string Key(string owner,string utterance)=>owner+"\u001f"+utterance; public void Claim(string owner,string utterance,ProvisionalReactionPath path,string claim){var k=Key(owner,utterance);if(_claims.TryGetValue(k,out var x)){if(x.Path==path&&x.Claim==claim)return;throw new InvalidOperationException("Reaction path already claimed");}if(_claims.Count>=ContextualProvisionalAdmissionSource.MaximumPathClaims)throw new InvalidOperationException("Claim capacity");_claims.Add(k,(path,claim));} public void Release(string owner,string utterance,ProvisionalReactionPath path,string claim){var k=Key(owner,utterance);if(!_claims.TryGetValue(k,out var x)||x.Path!=path||x.Claim!=claim)throw new InvalidOperationException("Claim identity mismatch");_claims.Remove(k);} public int Count=>_claims.Count; }

    public sealed class ContextualProvisionalReactionStore
    {
        private readonly V43ProposalTrustRegistry _proposals; private readonly DialogueAdmissionTrustRegistry _dialogue; private readonly ReactionPathClaimRegistry _claims; private readonly Dictionary<string,ContextualProvisionalReaction> _active=new Dictionary<string,ContextualProvisionalReaction>(StringComparer.Ordinal); private readonly HashSet<string> _seenUtterances=new HashSet<string>(StringComparer.Ordinal),_seenEvents=new HashSet<string>(StringComparer.Ordinal);
        public ContextualProvisionalReactionStore(V43ProposalTrustRegistry proposals,DialogueAdmissionTrustRegistry dialogue,ReactionPathClaimRegistry claims){_proposals=proposals;_dialogue=dialogue;_claims=claims;}
        public ContextualProvisionalAdmissionAttempt PrepareAttempt(ContextualAdmissionRequest request){_proposals.Verify(request.ProposalAttestation,request.Proposal);_dialogue.Verify(request.DialogueReceipt);var affect=Scale(request.Proposal.AffectDimensions,ContextualProvisionalAdmissionSource.AffectOverlayCapBps,request.Proposal.ConfidenceBps);var rel=request.Proposal.CounterpartId==request.DialogueReceipt.SpeakerId?Scale(request.Proposal.RelationshipConsiderations,ContextualProvisionalAdmissionSource.RelationshipOverlayCapBps,request.Proposal.ConfidenceBps):Array.Empty<MappedOverlayDimension>();var mode=request.Proposal.ConfidenceBps<2500?ContextualPresentationMode.None:(request.Proposal.IntensityBps>=6500?ContextualPresentationMode.Thought:ContextualPresentationMode.Icon);var id="contextual-attempt:"+ContextualProvisionalAdmissionSource.Hash(request.Fingerprint);var fp=ContextualProvisionalAdmissionSource.Hash(id+request.Fingerprint);return new ContextualProvisionalAdmissionAttempt(id,request,affect,rel,Array.Empty<string>(),mode,new[]{"V43_GROUNDED_COMPOUND_APPRAISAL"},fp);}
        public (ContextualProvisionalReaction Reaction,ObservedProvisionalAdmissionReceipt Receipt) Admit(ContextualAdmissionRequest request,ContextualProvisionalAdmissionAttempt attempt,long currentTick){if(attempt.RequestFingerprint!=request.Fingerprint||attempt.Outcome!=ContextualAdmissionOutcome.AttemptOnly)throw new ArgumentException("Attempt mismatch");if(currentTick<request.DialogueReceipt.AdmittedTick||currentTick>=attempt.DisplayedTick+ContextualProvisionalAdmissionSource.LifetimeTicks)throw new InvalidOperationException("Admission outside lifetime");var uk=request.Proposal.OwnerId+"|"+attempt.UtteranceId;var ek=request.Proposal.OwnerId+"|"+attempt.CurrentEventId;if(_seenUtterances.Contains(uk)||_seenEvents.Contains(ek))throw new InvalidOperationException("Replay rejected");if(_active.Count>=ContextualProvisionalAdmissionSource.MaximumGlobalActive||_active.Values.Count(x=>x.OwnerId==attempt.OwnerId)>=ContextualProvisionalAdmissionSource.MaximumActivePerOwner)throw new InvalidOperationException("Capacity");_claims.Claim(attempt.OwnerId,attempt.UtteranceId,ProvisionalReactionPath.ContextualV44,attempt.AttemptId);var rid="contextual-reaction:"+ContextualProvisionalAdmissionSource.Hash(attempt.Fingerprint);var receiptId="contextual-admission:"+ContextualProvisionalAdmissionSource.Hash(rid+currentTick);var receiptFp=ContextualProvisionalAdmissionSource.Hash(receiptId+attempt.Fingerprint);var receipt=new ObservedProvisionalAdmissionReceipt(receiptId,attempt.AttemptId,rid,attempt.OwnerId,attempt.UtteranceId,currentTick,attempt.CheckpointGeneration,attempt.CheckpointFingerprint,receiptFp);var reaction=new ContextualProvisionalReaction(rid,request,attempt,receiptFp,currentTick,ContextualReactionState.Prepared,ContextualProvisionalAdmissionSource.Hash(rid+receiptFp));_active.Add(rid,reaction);_seenUtterances.Add(uk);_seenEvents.Add(ek);_proposals.Consume(request.ProposalAttestation);_dialogue.Consume(request.DialogueReceipt);return(reaction,receipt);}
        public ContextualProvisionalReaction Activate(string reactionId,long currentTick){var r=Get(reactionId);if(currentTick<r.AdmittedTick)throw new InvalidOperationException("Activation precedes admission");if(currentTick>=r.ExpiresTick){Terminalize(r,ContextualReactionState.Expired);throw new InvalidOperationException("Expired");}r.State=ContextualReactionState.Active;return r;}
        public int Expire(long tick){var rows=_active.Values.Where(x=>tick>=x.ExpiresTick).ToList();foreach(var r in rows)Terminalize(r,ContextualReactionState.Expired);return rows.Count;}
        public int InvalidateCheckpoint(long generation,string fingerprint){var rows=_active.Values.Where(x=>x.CheckpointGeneration!=generation||x.CheckpointFingerprint!=fingerprint).ToList();foreach(var r in rows)Terminalize(r,ContextualReactionState.Discarded);return rows.Count;}
        public ContextualProvisionalReaction Get(string id)=>_active.TryGetValue(id,out var r)?r:throw new KeyNotFoundException(id); public int ActiveCount(string? owner=null)=>owner==null?_active.Count:_active.Values.Count(x=>x.OwnerId==owner);
        private void Terminalize(ContextualProvisionalReaction r,ContextualReactionState state){r.State=state;_active.Remove(r.ReactionId);_claims.Release(r.OwnerId,r.UtteranceId,ProvisionalReactionPath.ContextualV44,r.AttemptId);}
        private static IReadOnlyList<MappedOverlayDimension> Scale(IEnumerable<GroundedAppraisalDimensionProposal> rows,int cap,int confidence){var src=rows.Where(x=>x.ProposedBps!=0&&x.ConfidenceBps>0).OrderBy(x=>x.Dimension,StringComparer.Ordinal).ToList();var total=src.Sum(x=>Math.Abs((long)x.ProposedBps)*confidence/10000);if(total==0)return Array.Empty<MappedOverlayDimension>();return src.Select(x=>{var adj=(int)(x.ProposedBps*(long)confidence/10000);var value=total<=cap?adj:(int)(adj*(long)cap/total);return new MappedOverlayDimension(x.Dimension,x.ProposedBps,adj,value,cap);}).ToList();}
    }
}
