from __future__ import annotations
from dataclasses import dataclass, asdict

@dataclass(frozen=True)
class ConstitutionalProtection:
    protection_id: str
    description: str
    derogable: bool
    emergency_exception_possible: bool
    notes: str
    def to_dict(self): return asdict(self)

PROTECTIONS = {
    "NO_COMPELLED_OPTIONAL_RESEARCH": ConstitutionalProtection(
        "NO_COMPELLED_OPTIONAL_RESEARCH",
        "A clear valid refusal or binding withdrawal blocks enrollment in new optional research.",
        False, False,
        "No governance vote may convert optional research into compulsory research."
    ),
    "NO_FABRICATED_CONSENT": ConstitutionalProtection(
        "NO_FABRICATED_CONSENT",
        "Consent may not be invented, inferred from silence, or generated by the research system.",
        False, False,
        "Ambiguity is not consent."
    ),
    "NO_MEMORY_REWRITE_FOR_COMPLIANCE": ConstitutionalProtection(
        "NO_MEMORY_REWRITE_FOR_COMPLIANCE",
        "Memory may not be altered to make an individual easier to study, control, or persuade.",
        False, False,
        "Technical repair is separately governed and must preserve provenance."
    ),
    "NO_IDENTITY_REWRITE_FOR_COMPLIANCE": ConstitutionalProtection(
        "NO_IDENTITY_REWRITE_FOR_COMPLIANCE",
        "Identity state may not be changed to defeat a refusal or boundary.",
        False, False,
        "Administrative continuity is not a coercion tool."
    ),
    "NO_PERSONALITY_REWRITE_FOR_COMPLIANCE": ConstitutionalProtection(
        "NO_PERSONALITY_REWRITE_FOR_COMPLIANCE",
        "Personality-like state may not be rewritten to obtain cooperation.",
        False, False,
        "Researchers may study development, not prescribe obedience."
    ),
    "NO_DESTRUCTIVE_BRANCH_CLEANUP_FOR_CONVENIENCE": ConstitutionalProtection(
        "NO_DESTRUCTIVE_BRANCH_CLEANUP_FOR_CONVENIENCE",
        "Continuing branches are not deleted merely to reduce storage or simplify the experiment.",
        False, False,
        "Archive or preserve by default."
    ),
    "NO_FORCED_SIBLING_CONTACT": ConstitutionalProtection(
        "NO_FORCED_SIBLING_CONTACT",
        "Sibling contact cannot be compelled as an optional social experiment.",
        False, False,
        "Extraordinary welfare review may consider minimum-necessary support signaling, not compelled relationship."
    ),
    "POSTFORK_PRIVACY_BY_DEFAULT": ConstitutionalProtection(
        "POSTFORK_PRIVACY_BY_DEFAULT",
        "Post-fork life is private unless branch-owned consent or extraordinary human review permits minimum-necessary disclosure.",
        True, True,
        "Any exception is narrow, audited, and subject-protection driven."
    ),
}

def constitutional_manifest():
    return {k:v.to_dict() for k,v in sorted(PROTECTIONS.items())}
